import type { Config } from "tailwindcss";

/**
 * Tailwind theme ported verbatim from medexplorer.html so the live app
 * matches the design mock exactly.
 */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,ts,tsx,js}",
    "../../packages/ui/src/**/*.{vue,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f2f4f6",
        "secondary": "#006b5f",
        "on-surface-variant": "#45464d",
        "tertiary-fixed": "#d8e2ff",
        "on-secondary-container": "#006f64",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#adc6ff",
        "background": "#f7f9fb",
        "on-secondary": "#ffffff",
        "primary-fixed": "#dae2fd",
        "surface": "#f7f9fb",
        "tertiary": "#000000",
        "surface-container-highest": "#e0e3e5",
        "secondary-fixed": "#71f8e4",
        "primary": "#000000",
        "on-background": "#191c1e",
        "surface-variant": "#e0e3e5",
        "on-secondary-fixed": "#00201c",
        "secondary-fixed-dim": "#4fdbc8",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#eff1f3",
        "secondary-container": "#6df5e1",
        "primary-container": "#131b2e",
        "surface-tint": "#565e74",
        "on-secondary-fixed-variant": "#005048",
        "surface-dim": "#d8dadc",
        "surface-bright": "#f7f9fb",
        "inverse-primary": "#bec6e0",
        "on-primary": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "on-primary-fixed": "#131b2e",
        "on-tertiary-fixed": "#001a42",
        "on-tertiary-fixed-variant": "#004395",
        "on-tertiary-container": "#3980f4",
        "outline-variant": "#c6c6cd",
        "surface-container": "#eceef0",
        "primary-fixed-dim": "#bec6e0",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "inverse-surface": "#2d3133",
        "tertiary-container": "#001a42",
        "error": "#ba1a1a",
        "on-primary-container": "#7c839b",
        "on-primary-fixed-variant": "#3f465c",
        "outline": "#76777d",
        "on-surface": "#191c1e",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "4px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        "margin-desktop": "64px",
        gutter: "24px",
      },
      fontFamily: {
        "headline-xl": ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "body-sm": ["Manrope", "sans-serif"],
        "label-caps": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
      boxShadow: {
        "medical-glow": "0 10px 30px rgba(15,23,42,0.05)",
      },
    },
  },
  plugins: [],
} satisfies Config;
